### ISSUE TITLE
Barbarian Wild Soul purchase not connecting

### ISSUE THREAD

**Issue by mpayne216** [Fallenarmada/Avrae-Aliases#1]
I just recently subscribed to use the wild soul alias, but every time I try it tells me to purchase Battlerager to use it. I do have Wild Soul purchased with the entire TCoE on DnDBeyond so I think it should work.

**Comment by Fallenarmada** [comment]
The code is here https://github.com/Fallenarmada/Avrae-Aliases/blob/main/Barbarian

If you want to copy and paste it and use it as a personal alias. My plan was to edit all my aliases so they don't have official wording and could be used without needing to buy anything, but I haven't had time to do that unfortunately.
